trigger:
- main

pool:
  name: My-pool1

jobs:
- job: BuildAndRunDockerContainer
  displayName: 'Build and Run Docker Container'
  steps:
  - checkout: self

  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'docker-repository:latest'

  - script: 'docker run -it docker-repository:latest'
    displayName: 'Run Docker Container'
