trigger:
- main

pool:
  name: My-pool1

stages:
- stage: InstallerMavenEtOpenJDK
  jobs:
  - job: InstallerMavenEtOpenJDKJob
    displayName: "Installer Maven et OpenJDK"
    steps:
    - checkout: self

    - script: |
        # Récupérer des informations sur l'agent
        AGENT_NAME=$(My-pool1)
        AGENT_IP=$(My-pool1 -I | awk '{print $1}')

        # Installer OpenJDK
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk

        # Installer Maven
        sudo apt-get install -y maven

        # Afficher les versions installées
        java -version
        mvn --version

        # Afficher des informations sur la machine virtuelle
        echo "Machine virtuelle : $AGENT_NAME"
        echo "Adresse IP : $AGENT_IP"
      displayName: "Installer Maven et OpenJDK"
